server:
  port: 10100


---
spring.config.activate.on-profile: test

pactbroker:
  host: playtomic-nacho.pactflow.io
  port: 443
  scheme: https
  auth:
    token: jNlqXFqiA6__lb8oFfomFA

pact:
  provider:
    version: 1
  verifier:
    publishResults: true